In [109]:
import numpy as np
# sudoko  , rows and column sum should be 45 as 1 to 9 gives 45 , also 3*3 matrix total sum should be 45 then this called valid sudoku
s = np.array([[5,3,4,6,7,8,9,1,2],
             [6,7,2,1,9,5,3,4,8],
             [1,9,8,3,4,2,5,6,7],
             
             [8,5,9,7,6,1,4,2,3],
             [4,2,6,8,5,3,7,9,1],
             [7,1,3,9,2,4,8,5,6],
             
             [9,6,1,5,3,7,2,8,4],
             [2,8,7,4,1,9,6,3,5],
             [3,4,5,2,8,6,1,7,9]
            ])

In [110]:

row_sum = np.sum(s, axis=1)
row_sum


array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [111]:
for i in row_sum:
    if i != 45:
        print(" not valid rows")
        break
else:
    print(" valid for rows ")


 valid for rows 


In [112]:
col_sum = np.sum(s, axis=0)
col_sum

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [113]:
result= (col_sum == col_sum[0]).all()
#another method insteda of for loop to check all element are same

In [114]:
result

np.True_

In [115]:
if result ==True:
    print ("valid for column sudoku")
else :
    print("not valid for column")

valid for column sudoku


In [116]:
for i in range(0,9,3):
    for j in range(0,9,3):
        small_matrix = s[i:i+3,j:j+3]
        # print(small_matrix)
        n =np.sum(small_matrix)
        # print(n)
        if n!=45:
            print ("invalid sudoku")
            break
else:
    print ("valid sudoku")
    

valid sudoku


In [117]:
# 2. problem, general questions 
import numpy as np

In [118]:
#colums: [age,math marks, science marks]
data= np.array([
    [18,85,78],   #student1
    [19,92,88],    #student 2
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [119]:
#get the shape of the matrix
data.shape

(5, 3)

In [120]:
#find the avg age of the students
np.mean(data[:,0])
#for selecting first column

np.float64(18.4)

In [121]:
#extract math marks of all students
math_marks= data[0:5,1]
math_marks

array([85, 92, 76, 65, 90])

In [122]:
#find the highest science marks
sci_marks= data[0:5,2]
sci_marks


array([78, 88, 95, 70, 85])

In [123]:
sci_marks.max()
#another method np.max(data[:,2])

np.int64(95)

In [124]:
#get details of the students who scored more than 90 in maths
s= data[:,1]>90
s

array([False,  True, False, False, False])

In [125]:
data[s] # or data[s,:]   
# direct method- data[data[:,1]>90]

array([[19, 92, 88]])

In [126]:
# increase math marks of all students by 5
new= math_marks +5 
new
#or - data[0:5, 1] +5

array([90, 97, 81, 70, 95])

In [127]:
#find how many students are younger than 19
len(data[data[:,0]<19])


3

In [128]:
#calculate the average marks in each subject (column wise mean)
avg_math= np.mean(data[:,1])
avg_math

np.float64(81.6)

In [129]:
avg_sci= np.mean(data[:,2])
avg_sci

np.float64(83.2)

In [130]:
#another method
np.mean(data[:,0:], axis=0)

array([18.4, 81.6, 83.2])

In [131]:
#get data of students who scored at least 80 in both subject
data[(data[:,1]>= 80) & (data[:,2] >=80) ]

array([[19, 92, 88],
       [20, 90, 85]])

In [134]:
#replace all science marks <75 with 0
data[data[:,2]<75,2]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])

In [133]:
data[:,2] [data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])